export const BUSINESS = {
  name: "Gefence LLC",
  legalName: "Gefence LLC",
  owner: "Gary",
  phoneRaw: "8455511446",
  phoneDisplay: "(845) 551-1446",
  phoneHref: "tel:+18455511446",
  email: "Gefence1@gmail.com",
  emailHref: "mailto:Gefence1@gmail.com",
  city: "Greeley",
  state: "CO",
  region: "Northern Colorado",
  addressNote: "Serving Greeley & Northern Colorado",
  domain: "tntfenceco.com",
  slogan: "Fences Built to Last. Service You Can Trust.",
  tagline: "Greeley's fence installation specialists.",
  licenseNote: "Licensed & Insured — credentials on request",
  hours: [
    { d: "Mon–Fri", h: "7:00 AM – 6:00 PM" },
    { d: "Saturday", h: "8:00 AM – 2:00 PM" },
    { d: "Sunday", h: "Closed (calls returned next day)" },
  ],
  social: { facebook: "#", instagram: "#", google: "#" },
};
