export const FENCE_STYLES = [
  {
    key: "wood",
    name: "Wood Privacy",
    image: "/img/style-wood.jpg",
    description: "Classic cedar and treated-pine privacy fencing — warm, customizable, and the most popular choice for Greeley backyards.",
    pros: ["Best privacy and sound buffer", "Fully customizable height and style", "Lower upfront cost", "Easy to repair board-by-board"],
    cons: ["Needs stain/seal every few years", "Shorter lifespan than vinyl/metal"],
    bestFor: "Backyard privacy and traditional looks",
    lifespan: "15–20 years with maintenance",
    priceTier: "$$",
  },
  {
    key: "vinyl",
    name: "Vinyl",
    image: "/img/style-vinyl.jpg",
    description: "Low-maintenance vinyl fencing that never needs paint or stain and shrugs off Colorado sun and moisture.",
    pros: ["Virtually maintenance-free", "Won't rot, warp, or peel", "Clean modern look", "Long lifespan"],
    cons: ["Higher upfront cost", "Fewer repair options if cracked"],
    bestFor: "Owners who want privacy with zero upkeep",
    lifespan: "25–30+ years",
    priceTier: "$$$",
  },
  {
    key: "chainlink",
    name: "Chain-Link",
    image: "/img/style-chainlink.jpg",
    description: "Economical, durable boundary and security fencing for yards, pets, and light-commercial use.",
    pros: ["Most budget-friendly", "Extremely durable", "Great for pets and large areas", "Optional privacy slats"],
    cons: ["Minimal privacy by default", "Utilitarian appearance"],
    bestFor: "Pet containment, security, large perimeters",
    lifespan: "20+ years",
    priceTier: "$",
  },
  {
    key: "aluminum",
    name: "Aluminum / Ornamental",
    image: "/img/style-aluminum.jpg",
    description: "Powder-coated ornamental aluminum that delivers a wrought-iron look without the rust or maintenance.",
    pros: ["Elegant, high-end curb appeal", "Rust-proof and low maintenance", "Great for pools and slopes", "Long lifespan"],
    cons: ["No privacy", "Higher cost than chain-link"],
    bestFor: "Front yards, pools, decorative boundaries",
    lifespan: "30+ years",
    priceTier: "$$$",
  },
  {
    key: "composite",
    name: "Composite",
    image: "/img/style-composite.jpg",
    description: "Modern composite panels combining the look of wood with the durability and low upkeep of synthetics.",
    pros: ["Wood look, minimal maintenance", "Won't rot or splinter", "Strong privacy", "Premium modern aesthetic"],
    cons: ["Highest upfront cost", "Heavier — needs solid posts"],
    bestFor: "Premium privacy with a contemporary look",
    lifespan: "25–30+ years",
    priceTier: "$$$$",
  },
  {
    key: "splitrail",
    name: "Split-Rail",
    image: "/img/style-splitrail.jpg",
    description: "Rustic split-rail and ranch fencing that defines property lines and pasture without blocking the view.",
    pros: ["Open, rural aesthetic", "Affordable for long runs", "Quick to install", "Easy to add mesh for pets"],
    cons: ["No privacy or security", "Not for small yards"],
    bestFor: "Acreage, pastures, property lines",
    lifespan: "15–20 years",
    priceTier: "$$",
  },
];
